language: minimal

matrix:
  include:
    - name: "Debian 10 (Buster)"
      os: linux
      sudo: required
      services:
        - docker
      env: 
        - CI_TYPE=deb
        - WORKSPACE=${TRAVIS_BUILD_DIR}
        - RUNNER="docker exec -w ${TRAVIS_BUILD_DIR} -e WORKSPACE=${WORKSPACE} debian_buster"
      before_install:
        - docker run -di -v ${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR} --name debian_buster --rm debian:buster
      after_success:
        - docker kill debian_buster
    
    - name: "Ubuntu 18.04 (Bionic)"
      os: linux
      sudo: required
      services:
        - docker
      env: 
        - CI_TYPE=deb
        - WORKSPACE=${TRAVIS_BUILD_DIR}
        - RUNNER="docker exec -w ${TRAVIS_BUILD_DIR} -e WORKSPACE=${WORKSPACE} -e DEBIAN_FRONTEND=noninteractive ubuntu_bionic"
      before_install:
        - docker run -di -v ${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR} --name ubuntu_bionic --rm ubuntu:bionic
      after_success:
        - docker kill ubuntu_bionic

install: ${RUNNER} ./.ci/${CI_TYPE}/install
script: ${RUNNER} ./.ci/${CI_TYPE}/build && ${RUNNER} ./.ci/${CI_TYPE}/post_build
